Fix convention of PolynomialTensor basis change
quantumlib/OpenFermion pull request #805
Opened 2022-10-10 04:47 UTC by aoowweenn

In general, we rotate a matrix M to M' is to apply a rotation matrix R: M' = R @ M @ R.T
The corresponding Einstein notation is
M'^{p_1p_2} = R^{p_1}_{a_1} R^{p_2}_{b_1} M^{a_1a_2}

2026-06-02 21:53 UTC, mhucka commented
@arettig Would you be able to take a look at this and check the technical correctness? (No rush.)

2026-06-05 17:58 UTC, arettig requested changes
This is a good catch. The `PolynomialTensor` rotation code currently does not match the expression in the [documentation](https://quantumai.google/openfermion/tutorials/circuits_1_basis_change). We should change this to match standard convention (and our own documentation), but this is a potentially breaking change for anyone using this function currently.

It would also be a good idea to change the 90 degree rotation test added in this PR to some different rotation as this test actually passes with the current (incorrect) implementation.

2026-06-05 17:58 UTC, arettig commented on src/openfermion/ops/representations/polynomial_tensor_test.py
> +    def test_rotate_basis_90deg(self):
This test actually does not catch the bug you pointed out since for this specific case $$U^T M U$$ gives the same results as $$U M U^T$$. It would be a good idea to change this test to use a different basis rotation.

2026-06-16 19:54 UTC, arettig commented on src/openfermion/ops/representations/polynomial_tensor_test.py
> +    def test_rotate_basis_90deg(self):
Changed to a cyclical rotation test, which can distinguish between the incorrect previous code and the current fixed code.

2026-06-17 15:12 UTC, arettig approved these changes
LGTM

2026-06-17 16:57 UTC, merged